#!/bin/bash
# ==================================================================
# Terminal Claude Sync Environment Setup Script
# ==================================================================
# This script interactively generates/updates the .env file
# for Docker development environment configuration.
#
# Usage:
#   ./setup_env.sh              # Interactive mode
#   ./setup_env.sh --non-interactive  # Non-interactive mode (uses defaults)
# ==================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"
ENV_EXAMPLE="${SCRIPT_DIR}/.env.example"

# Parse arguments
NON_INTERACTIVE=false
for arg in "$@"; do
    case $arg in
        --non-interactive|-n)
            NON_INTERACTIVE=true
            shift
            ;;
    esac
done

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Helper functions
print_header() {
    echo -e "${BLUE}============================================================${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}============================================================${NC}"
}

print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

# Load existing .env values if present
load_existing_env() {
    if [[ -f "$ENV_FILE" ]]; then
        print_warning "Found existing .env file"
        echo ""
        read -p "Do you want to preserve existing values? (y/n) " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            # shellcheck disable=SC1090
            source "$ENV_FILE"
            print_success "Loaded existing configuration"
            return 0
        fi
    fi
    return 1
}

# Prompt for a value with optional default
prompt_value() {
    local var_name="$1"
    local description="$2"
    local default_value="$3"
    local is_secret="$4"

    echo ""
    echo -e "${YELLOW}${description}${NC}"

    local current_value="${!var_name}"
    local default_display="${default_value:-<empty>}"

    if [[ -n "$current_value" ]]; then
        echo -e "Current value: ${BLUE}${current_value}${NC}"
    else
        echo -e "Default: ${BLUE}${default_display}${NC}"
    fi

    if [[ "$is_secret" == "true" ]]; then
        read -p "Enter value (leave empty to use current/default): " -s input_value
        echo ""
    else
        read -p "Enter value (leave empty to use current/default): " input_value
    fi

    if [[ -n "$input_value" ]]; then
        eval "${var_name}='${input_value}'"
    elif [[ -z "$current_value" && -n "$default_value" ]]; then
        eval "${var_name}='${default_value}'"
    fi
}

# Main setup function
main() {
    if [[ "$NON_INTERACTIVE" == "true" ]]; then
        echo "Running in non-interactive mode..."

        # Check if .env already exists
        if [[ -f "$ENV_FILE" ]]; then
            echo ".env file already exists, skipping setup"
            exit 0
        fi

        # Generate minimal .env with defaults
        cat > "$ENV_FILE" << EOF
# ==================================================================
# Terminal Claude Sync Development Environment Configuration
# Generated by setup_env.sh on $(date)
# ==================================================================

# User Configuration (auto-detected)
UID=$(id -u)
GID=$(id -g)

# Feishu Configuration (REQUIRED)
# Get from: https://open.feishu.cn/app
APP_ID=
APP_SECRET=

# Claude Code Configuration (REQUIRED)
ANTHROPIC_AUTH_TOKEN=
ANTHROPIC_BASE_URL=

# Bridge Server Port
BRIDGE_PORT=8082
EOF
        echo ".env file created with defaults. Please edit with your credentials."
        exit 0
    fi

    print_header "Terminal Claude Sync Environment Setup"
    echo ""
    echo "This script will help you configure the development environment."
    echo "Press Enter to skip/keep existing values."
    echo ""

    # Initialize variables
    UID_VAL=""
    GID_VAL=""
    APP_ID=""
    APP_SECRET=""
    ANTHROPIC_AUTH_TOKEN=""
    ANTHROPIC_BASE_URL=""
    BRIDGE_PORT=""

    # Try to load existing values
    load_existing_env || true

    # Auto-detect UID/GID
    if [[ -z "$UID" ]]; then
        UID_VAL="$(id -u)"
    else
        UID_VAL="$UID"
    fi

    if [[ -z "$GID" ]]; then
        GID_VAL="$(id -g)"
    else
        GID_VAL="$GID"
    fi

    print_header "User Configuration"
    prompt_value "UID_VAL" "User UID (for Docker permissions)" "$UID_VAL" "false"
    prompt_value "GID_VAL" "User GID (for Docker permissions)" "$GID_VAL" "false"

    print_header "Feishu Configuration (REQUIRED)"
    echo ""
    echo -e "${YELLOW}Get your App ID and Secret from: https://open.feishu.cn/app${NC}"
    prompt_value "APP_ID" "Feishu App ID" "$APP_ID" "false"
    prompt_value "APP_SECRET" "Feishu App Secret" "$APP_SECRET" "true"

    print_header "Claude Code Configuration (REQUIRED)"
    prompt_value "ANTHROPIC_AUTH_TOKEN" "Anthropic Auth Token" "$ANTHROPIC_AUTH_TOKEN" "true"
    prompt_value "ANTHROPIC_BASE_URL" "API Base URL (optional, for proxy)" "$ANTHROPIC_BASE_URL" "false"

    print_header "Bridge Server Configuration"
    prompt_value "BRIDGE_PORT" "Bridge Server Port" "${BRIDGE_PORT:-8082}" "false"

    # Generate .env file
    print_header "Generating .env File"
    echo ""

    cat > "$ENV_FILE" << EOF
# ==================================================================
# Terminal Claude Sync Development Environment Configuration
# Generated by setup_env.sh on $(date)
# ==================================================================

# ------------------------------------------------------------------
# User Configuration
# ------------------------------------------------------------------
UID=${UID_VAL}
GID=${GID_VAL}

# ------------------------------------------------------------------
# Feishu Configuration (REQUIRED)
# ------------------------------------------------------------------
APP_ID=${APP_ID}
APP_SECRET=${APP_SECRET}

# ------------------------------------------------------------------
# Claude Code Configuration (REQUIRED)
# ------------------------------------------------------------------
ANTHROPIC_AUTH_TOKEN=${ANTHROPIC_AUTH_TOKEN}
ANTHROPIC_BASE_URL=${ANTHROPIC_BASE_URL}

# ------------------------------------------------------------------
# Bridge Server Configuration
# ------------------------------------------------------------------
BRIDGE_PORT=${BRIDGE_PORT}
EOF

    print_success ".env file created at ${ENV_FILE}"
    echo ""

    # Show summary
    print_header "Configuration Summary"
    echo -e "UID:            ${BLUE}${UID_VAL}${NC}"
    echo -e "GID:            ${BLUE}${GID_VAL}${NC}"
    echo -e "App ID:         ${BLUE}${APP_ID}${NC}"
    echo -e "App Secret:     ${BLUE}${APP_SECRET:0:8}...${NC}"
    echo -e "Auth Token:     ${BLUE}${ANTHROPIC_AUTH_TOKEN:0:10}...${NC}"
    echo -e "Base URL:       ${BLUE}${ANTHROPIC_BASE_URL:-<default>}${NC}"
    echo -e "Bridge Port:    ${BLUE}${BRIDGE_PORT}${NC}"
    echo ""

    print_success "Setup complete!"
    echo ""
    echo "Next steps:"
    echo "  1. Run: cd ${SCRIPT_DIR}"
    echo "  2. Run: docker-compose up -d"
    echo "  3. Run: docker-compose exec app bash"
    echo "  4. Inside container: python -m src.bridge"
    echo "  5. In another terminal: python -m src.terminal_client"
    echo ""
}

# Run main function
main "$@"